apiVersion: apps/v1
kind: Deployment
metadata:
  name: aman-test
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 3
  selector:
    matchLabels:
      app: aman-test
  template:
    metadata:
      labels:
        app: aman-test
    spec:
      containers:
      - name: aman-test
        image: 529448940572.dkr.ecr.ap-south-1.amazonaws.com/aman/nodejs-test
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 0.1
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: aman-lb
spec:
  selector:
    app: aman-test
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aman-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aman-test
  minReplicas: 10
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50
